### ISSUE TITLE
Resolution scaling doesn't work properly

### ISSUE THREAD

**Issue by TecFox** [milkytracker/MilkyTracker#101]
The scale level under Config > Layout > Resolutions scales the graphics but not the window resulting in the rest of the tracker getting cut off:

![milkytracker-1 0-scaling](https://cloud.githubusercontent.com/assets/29158800/26751767/bbc3221e-4841-11e7-8f2e-781486535b53.png)

Version: 1.0.0, Windows 7 64-Bit

**Comment by SaxxonPike** [comment]
This happens also on my machine. Setting the resolution to 640x480 seems to work fine, but if I set the scale to 2x and select a custom resolution of 1280x960 (twice the size in both dimensions) the graphics still end up getting cut off.

Version 1.0.0, Win10 x64 here.
