### ISSUE TITLE
jam channels not working after changing mixer settings

### ISSUE THREAD

**Issue by beesbeesbees2** [milkytracker/MilkyTracker#118]
Jam channels worked fine in 0.90.85, but the option seems to have no effect with 1.01.00 (jamming is always one channel)

**Comment by Deltafire** [comment]
It seems to work as intended for me, could you provide a bit more detail please?

**Comment by beesbeesbees2** [comment]
Works now. Seems that it breaks if the buffer size or mixer resolution is changed, and works again upon either restarting the program or changing the sound driver.

**Comment by Deltafire** [comment]
Confirmed!

**Comment by teimoso** [comment]
Some more information on this issue (may or may not be useful, maybe some stuff only happens on my end?):

When entering the `Config` menu and applying changes (`OK` or `Apply`), jam channels stop working. This happens even if you don't make any changes, and regardless of what section you're in (`I/O`, `Layout`...)

In `I/O`, if you change the jam channel amount to a value that's different than it previously was and apply, the jam channels will work again.

##### Example
1. Enter `Config`
2. In `I/O`, change jam channel amount from (ex.) `55` to `54`, and click `OK` or `Apply`.

The jam channels should still function. If you instead change from `55` to `54`, and before applying, go back to `55` and _then_ apply, the jam channels won't work.

MIDI input is also affected by the issue.

Contrary to the issue report, changing sound drivers doesn't fix the jam channels even though I remember that working at some point. Maybe something changed between 1.01 and 1.02?

###### Operating System:&nbsp; &nbsp; Windows 7 (64-bit)
