### ISSUE TITLE
Could pattern wrapping be the default?

### ISSUE THREAD

**Issue by martinmosegaard** [milkytracker/MilkyTracker#130]
From FT2 I seem to recall that if I scrolled down a pattern with the arrow down key, it would continue from the top after reaching the bottom.

The behavior in MilkyTracker is to stop once the bottom is reached. This makes it kinda hard to go back to the top.

Instead, when arrow down is pressed on the last row of a pattern, it could move back to the top?

**Comment by SyntaxErrol** [comment]
Pattern wrapping is toggleable, either via Ctrl/Cmd-W or the tiniest little [W] button above the song title field.

**Comment by martinmosegaard** [comment]
Got it, awesome! Petition to make wrapping turned on by default? Otherwise I will just close this issue again.

**Comment by martinmosegaard** [comment]
Hmm ... from the code it looks indeed like pattern wrapping is the default. It also seems that the setting is persisted between restarts. Perhaps I have unadvertently switched it off at some point.

Closing this issue.
