### ISSUE TITLE
OSX fullscreen

### ISSUE THREAD

**Issue by sircola** [milkytracker/MilkyTracker#134]
alt-cmd-F won't switch to fullscreen.
I have a bt speaker that I use with my notebook and I can't switch to it in "driver select", only builtin speakers.
This is on mac. Ty for porting the best tracker!

**Comment by Deltafire** [comment]
Shift-cmd-F toggles fullscreen, the manual seems to be incorrect.

I think you need to select your BT speaker before starting Milkytracker (right click on the speaker icon in the OSX menu bar).
