### ISSUE TITLE
Separate options for Protracker and XM mode

### ISSUE THREAD

**Issue by xracecar** [milkytracker/MilkyTracker#137]
So when I go into the Options button, I can chose my Protracker module panning settings, but I want to keep those settings only for Protracker modules and not effect extended modules.

**Comment by SyntaxErrol** [comment]
The Default panning settings don't affect Fasttracker 2.x mode, hinted by the option being disabled when FT2 mode is selected.

**Comment by Deltafire** [comment]
That makes sense.
