### ISSUE TITLE
Version 1.01.00 is ambiguous

### ISSUE THREAD

**Issue by jcowgill** [milkytracker/MilkyTracker#144]
There are two different released versions of MilkyTracker taged with the same version number:
* v1.01.00 (2017-07-29 - 1b85020cfaae791c50f4daa4566d12ef224f4eed)
* 1.01.00 (2017-11-16 - 99ab119cb19b1398570880ef9cd111b11f9bd643)

Please use different version numbers.

**Comment by Deltafire** [comment]
Sorry, I'm testing appveyor - please ignore 1.01.00.
