### ISSUE TITLE
Setup Travis-CI for autobuild AppImage (portable package for Linux)

### ISSUE THREAD

**Issue by ghost** [milkytracker/MilkyTracker#149]
Providing an <a href="https://appimage.org">AppImage</a> would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, <a href="http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80">make it executable</a>, and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with appimaged
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the <a href="https://appimage.github.io/apps">AppImageHub</a> central directory of available AppImages

<a href="https://github.com/AppImage/AppImageKit/wiki/AppImages">Here is an overview</a> of some projects that are already distributing upstream-provided, official AppImages.

https://github.com/probonopd/linuxdeployqt has lots of real-world examples on how to do this. Let @probonopd know if something is not clear or you need some help.

https://github.com/probonopd/uploadtool script will help you setup Travis-CI for uploading built AppImage's automatically back to Github repo in "Releases" section.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net

Ask @probonopd for help you on Github ;-)

**Comment by Symbian9** [comment]
For the record, unofficial AppImage's published here:

- https://modarchive.org/forums/index.php?topic=4025.0

**Comment by probonopd** [comment]
Given this
https://github.com/milkytracker/MilkyTracker/blob/master/.travis.yml
it should be rather straightforward to produce AppImages from the Travis CI builds like in the examples on https://github.com/probonopd/linuxdeployqt.

**Comment by MIfeanyi** [comment]
lets do it

**Comment by probonopd** [comment]
Let me know if you are running into any issues or get stuck, I'm happy to help.

**Comment by Symbian9** [comment]
Any news?

**Comment by probonopd** [comment]
I am happy to help if someone from the project is working on this and is running into issues.

**Comment by Deltafire** [comment]
Perhaps someone could submit a pull request for this?

**Comment by MIfeanyi** [comment]
I'm familiar at least at a basic level with using AppImage with packaging Love2D & also just built a AppImage for Milky 0.90.85 . I'm going to try building from source but I'm not to familiar with travis... or good with CMake. For example I dont understand how the "script" portion of the example yaml for [linuxdeployqt](https://github.com/probonopd/linuxdeployqt)

This was all I could put together. missing the script, after_success, & branch
`language: cpp
git:
    submodules: true

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required
        addons:
            apt:
                packages:
                   - libjack-dev
                   - librtmidi-dev
                   - libsdl2-dev
                   - libzzip-dev
        script: &cmake_build
          - mkdir build
          - pushd build
          - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 ..
          - cmake --build .
          - cpack
          - popd
      - os: osx
        before_install:
          - brew update
          - brew install xmlto
          - pushd resources/pictures/docicons/osx
          - wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/docerator/docerator-2.0.zip
          - unzip docerator-2.0.zip -d docerator
          - rm docerator-2.0.zip
          - /usr/bin/python genicons.py
          - popd
          - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
          - sudo apt-get update -qq
	install:
	  - sudo apt-get -y install qt59base
  	  - source /opt/qt*/bin/qt*-env.sh
        script: *cmake_build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Vr2TAgHrYnMp95PUmGnzl3E2dMqBTe3E/JZZAInWC8Ifx1hCF0SI085svFg902kFhnZJhMFBukP/hNu6UAm/exTdAByks57Af9oJTCxrUIYhYs2sasKjmSKPjRD5rFB+zqZSlq/DKzQZTBZBYUn2w3f4otrbNB6vBayNgWMtKdEtS1GI6e9pxKQcvxJodi/4RNgws6l5sQ59aPSPGK0XnOSLu5HPGC4QLpdQVSw5/Rzn5Fcw3zPVYOs7ZV/t7ptmR7T+MjFSE7HBMJlUPflHWA+L3jjx8ngYkz+W0pNsXxomRQVCLhGlGo0F6EEijOt1TvLhqMTVWrMgNjK9pxlgZEMWTho8/44kLQ5ABGuqql+uhTtJXI4dLmrrSPnCDHvVd7j8cwQDptYvRaEhzZmxNAB+xhqWdMDzkL7DouRcFzuKWTCWPFablVDXElcODO+xqWcU62gO/xEww7Y1mC9GC5zpmOgA7198JxeIM/o5eiMsj1J24KK+2WJH3t65hqGNhRfHgoR24LfkylhU+MFEnM5ZQM/21IGfeA/bszKDitDfIuNMOCSQqiD/fIKFsqOrKRvMi5cp1XvHzQTIR5x+BWS6zQwQk0RCaM7d7FKTtT3w0cm0aNAD3f0MfdU3BKH9YG5DT5DNvsoP613bg50tVgarTX5PwNOosQU/rSysLIg=
  file_glob: true
  file: build/milkytracker-*
  on:
    tags: true`

**Comment by MIfeanyi** [comment]
actually please see [this](https://github.com/MIfeanyi/MilkyTracker/blob/5d92b4e960393ed803820e77a2d38cea732d94ea/.travis.yml)

**Comment by probonopd** [comment]
Seems to be mixed up because there are Linux commands in the `os: osx` section and there is `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.7` in the `os: linux` section. Shouldn't it be the other way around?

What does `script: &cmake_build` mean?

> For example I dont understand how the "script" portion of the example yaml for linuxdeployqt

Let me annotate it:

```
script:
# Configure the application in the release configuration with the prefix /usr (as for any Qt based application), has nothing to do with AppImage specifically
  - qmake CONFIG+=release PREFIX=/usr
# Compile the application, has nothing to do with AppImage specifically
  - make -j$(nproc)
# Install the application, but inside an appdir/ directory (rather than in / as you would normally do)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find
# Download the linuxdeployqt tool which will transform the contents of the appdir/ directory into an AppImage
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
# Make it executable
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
# Unset variables that were set earlier, so that linuxdeployqt can work correctly
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
# Export the VERSION environment variable so that the linuxdeployqt tool knows the version of the application to be put into the AppImage
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
# Run linuxdeployqt so that it copies dependencies into the appdir/ directory; tell it (by pointing to the desktop file) which application is the main application inside the appdir/; also tell it to not just bundle Qt but other libraries, too
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
# Run linuxdeployqt again and tell it to convert the appdir/ directory to an AppImage file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
```

**Comment by MIfeanyi** [comment]
@probonopd Thank you for going into such detail for me. I am not a travis CI / CMake user so I'll have to do a bit more research & get a little familiar with MT specific stuff. Hopefully I can get it working over the weekend. Does anyone know if Travis CI works on forks?

**Comment by probonopd** [comment]
Yes, it works on forks just as normal.

**Comment by MIfeanyi** [comment]
I'm getting a lot closer. I still need to clean up the osx script that I messed up but here's the current [yaml](https://github.com/MIfeanyi/MilkyTracker/blob/80dfe32bf4ca8a800954e6d605229130a40c4735/.travis.yml) . This is the latest TCI but the last command fails:
` ./linuxdeployqt-continuous-x86_64.AppImage *.desktop -appimage`
Looking at the output it seems like linuxdeployqt is pulling the binary from Cpack instead of the binary I copied... should I need to copy the files into a new directory?

**Comment by MIfeanyi** [comment]
I have it decently working but what's the best way to integrate this? I dont think it should stay in the [yaml](https://github.com/MIfeanyi/MilkyTracker/pull/1) as it's quite a bit for just one build esp if others wanted to add in snaps, flatpak, etc.

**Comment by probonopd** [comment]
I think it's good to have it in `.travis.yml` - does it produce a working AppImage?

**Comment by MIfeanyi** [comment]
@Deltafire  What are your thoughts? Should I have AppImage generation in it's own script & just put minimal lines into the yaml? What would have to stay is linuxdeployqt ppa info, the script, & adding Appimage into releases.

**Comment by Deltafire** [comment]
I think it should be in .travis.yaml, perhaps with a comment to specify which build steps are specific to appimage.

**Comment by coderofsalvation** [comment]
I've created a more or less working milkytracker AppImage (though using `appveyor.yml` since I didn't know about this thread).

**Comment by coderofsalvation** [comment]
AppImage is now created automatically since [v1.04](https://github.com/milkytracker/MilkyTracker/pull/314) 🎉
