### ISSUE TITLE
FontLibrary.cpp trips Windows Defender, recognized as Trojan:Script/Cloxer.A!cl

### ISSUE THREAD

**Issue by rogersachan** [milkytracker/MilkyTracker#153]
![image](https://user-images.githubusercontent.com/7173984/37637375-bae9a5e0-2bdd-11e8-942e-54740d4ead89.png)

Is this a legitimate result or just a false positive?

**Comment by Deltafire** [comment]
False positive - FontLibrary.cpp contains only fonts!
