### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [milkytracker/MilkyTracker#155]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for MilkyTracker. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by Deltafire** [comment]
We already have a release tarball, the latest is available at:

[https://github.com/milkytracker/MilkyTracker/releases/download/v1.02.00/milkytracker-1.02.00.tar.gz](https://github.com/milkytracker/MilkyTracker/releases/download/v1.02.00/milkytracker-1.02.00.tar.gz)

**Comment by Deltafire** [comment]
You're right, I had assumed it was the source but hadn't actually checked it. Reopening this issue.
