### ISSUE TITLE
64 bit support.

### ISSUE THREAD

**Issue by Calypso314** [milkytracker/MilkyTracker#159]
It seems that upcoming Mac OS Mojave will be the last version to support 32 bit apps. Can we get 64 bit port, so that we can use MilkyTracker even in the future?

**Comment by Deltafire** [comment]
It seems that 32-bit apps are still supported in OSX 10.14/Mojave, but XCode will no longer support building them.  As soon as XCode drops support for 32-bit targets MilkyTracker will do the same.

To provide the greatest compatibility we are always producing binaries for the oldest supported XCode target (currently OSX 10.7/Lion).

**Comment by SpaceLlama1** [comment]
OK, so if I understand correctly, you will make 64-bit version when Apple officially kills all support for 32-bit apps.

Thank you very much.
