### ISSUE TITLE
Does not want to launch on Ubuntu Bionic

### ISSUE THREAD

**Issue by vitalkanev** [milkytracker/MilkyTracker#160]
Steps to reproduce: <OL>
<LI>Download <CODE>milkytracker-1.02.00.tar.gz</CODE> and extract it</LI>
<LI>Execute <CODE>./bin/milkytracker</CODE></LI>
</OL>

<H2>Expected behaviour</H2>
<P>MilkyTracker window is shown</P>

<H2>Actual behaviour</H2>
<P>Nothing. System is frozen. I also had to find these lines from <CODE>/var/log/syslog</CODE>:</P>

```
Jul  1 16:15:12 Clayside compiz[1601]: ERROR 2018-07-01 16:15:12 unity.decoration.shape DecorationsShape.cpp:73 Failed to get shape rectangles
Jul  1 16:15:12 Clayside compiz[1601]: /usr/bin/compiz (opengl) - Error: Impossible to bind a pixmap bigger than 16384x16384 to texture.
Jul  1 16:15:12 Clayside bamfdaemon[1378]: Got an X error: BadWindow (invalid Window parameter)
```

<H2>System configuration:</H2>

**OS**: Ubuntu 18.04
**X.org version** (yeah I think this is proably needed):

```
X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-119-generic x86_64 Ubuntu
Current Operating System: Linux Clayside 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-23-generic root=UUID=<...> ro quiet splash vt.handoff=1
Build Date: 13 April 2018  08:07:36PM
xorg-server 2:1.19.6-1ubuntu4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

**MilkyTracker version**: 1.02.00
**Desktop Environment**: Unity (installed via <CODE>sudo apt install ubuntu-unity-desktop</CODE>)
**Window Manager**: Compiz

**Comment by Deltafire** [comment]
Looks like it's trying to open a huge window - you could try deleting your milkytracker config file to reset to defaults (probably in HOME/.config/milkytracker).  If that fails, try building from source or using the distro provided package.
