### ISSUE TITLE
No way to change resolution after accidentally setting it too high

### ISSUE THREAD

**Issue by ideronme** [milkytracker/MilkyTracker#166]
I changed the resolution to the highest it could go a few moments after first opening the program, just on instinct, and now there's no way for me to get back over to the resolution controls. I've looked around on the internet for a while for fixes for this, and haven't found anything that works. With the newest versions of MT, there seems to be no accessible CFG file that I can see. Any help would be greatly appreciated!

**Comment by zetamek** [comment]
I can't replicate the problem, as MT always fits my screen, no matter the resolution. You could just download it again for now.

**Comment by ideronme** [comment]
This is also part of my issue: redownloading the program does nothing to help me. No matter which version I download, it's always zoomed in to the same resolution.

**Comment by zetamek** [comment]
So, I think this issue should be closed already, since Deltafire's answer is the solution.
