### ISSUE TITLE
OSX: Remapped modifier keys are interpreted as being from the opposite side

### ISSUE THREAD

**Issue by CoryAlexMartin** [milkytracker/MilkyTracker#167]
1. Swap "Control" and "Command" in System Preferences > Keyboard > Modifier Keys... ([example](https://i.imgur.com/en1P6w9.png))
2. Try to perform any of the standard shortcuts that require Command, such as cutting, by using the Left Control key.
- Results: None of the functions will work, unless you use the Right Control key. If you switch your edit mode to Fasttracker II, the Left Control key will trigger the "Play song from current order" shortcut, which should only occur with the Right Control key. Left and right appear to be swapped.

**Comment by Deltafire** [comment]
I'd say this is a bug/feature of MacOS and not MilkyTracker.
