### ISSUE TITLE
Linux: Wrong window scaling (Blur)

### ISSUE THREAD

**Issue by ghost** [milkytracker/MilkyTracker#171]
I don't know everyone has this problem or not, but this blur very annoy me.
![2019-02-01_15-05](https://user-images.githubusercontent.com/31385423/52125015-abdbb100-2633-11e9-8eef-ef7d4d322e07.png)

**Comment by 44100hertz** [comment]
it looks a little better if you set the window scale to 2x

**Comment by Deltafire** [comment]
I think this is because the window has been rescaled using the window resize handle.  Try changing the resolution in the Config menu.

Unfortunately MilkyTracker needs a restart for this to take effect.
