### ISSUE TITLE
Horizontal trackpad scrolling is backwards in Linux

### ISSUE THREAD

**Issue by zebzorb** [milkytracker/MilkyTracker#178]
Scrolling works as expected on my Mac, but in Linux it's reversed -- vertical scrolling is normal, but horizontally scrolling to the left causes it to scroll to the right.

I'm using KDE neon (Ubuntu 18.04 LTS with bleeding edge KDE packages) with libinput as my trackpad driver (in X, not Wayland). Horizontal scrolling works as expected in everything else (Firefox, Dolphin, Gimp, etc).

It's not really a huge deal because I usually use MilkyTracker with an external keyboard, mouse, and monitor, but I figured I should mention anyway :stuck_out_tongue_closed_eyes:

**Comment by Deltafire** [comment]
Tried this on Windows today and it's different again; horizontal scrolling causes the cursor to move, as if the left/right cursor keys were pressed.  Seems that only the Mac port works correctly.

**Comment by Deltafire** [comment]
Fixed in 716b3f9a5302373ff84fccaf1872992eb0ed29f0.
