### ISSUE TITLE
Note-off is saved as B-7 in .mod files

### ISSUE THREAD

**Issue by trevorparscal** [milkytracker/MilkyTracker#179]
When saving .mod files, note-off is saved as a B-7, triggering the pattern incompatibility dialog and loading back into the program as a B-7 instead of a note-off.

Tested on MilkyTracker v0.90.86 and v1.02.00 on macOS Mojave 10.14.5 (18F132).

To reproduce:

1. Create a new file
2. In "Config" change to "Amiga Frequencies" (for .mod compatibility)
3. In "Disk Op." change format the ".mod" and then click "Save As..." and save to a file
4. In the tracker, enter any note between C-3 and B-5
5. Click Save (works fine)
6. In the next row, enter a "note-off" (1 key for me on macOS)
5. Click Save, there will be a warning about pattern incompatibility
6. Close the file
7. Open the file and notice that the note-off is now a B-7

**Comment by SyntaxErrol** [comment]
.MODs don't have note-off, so that's why can't actually use them. Use Cxx, A0x, ECx or the like instead. Not sure if the B-7 makes sense but it's an invalid entry either way.

**Comment by trevorparscal** [comment]
Thank you! This helps a lot.
