### ISSUE TITLE
unexpected behavior with pattern cut/copy/paste and linux desktop switching

### ISSUE THREAD

**Issue by inversephase** [milkytracker/MilkyTracker#180]
To be honest, I'm not sure if this is entirely resolvable within milkytracker, but hopefully we can figure it out. I'm running milky 1.02.00 on a machine with XFCE 4.12.5 (revision d730ebb6) built against GTK+-2.24.32.

If you place Milkytracker on desktop 3, and then switch from another desktop to the one with milkytracker on it, the key to do so is ctrl-f3. this is the same key as pattern cut. yes I could just change the key, but the weird thing is that pattern cut does not normally work. it DOES work when I switch desktops to milky, and I get an accidental nuked pattern which I must then undo. Is the window manager trapping it? Is milky somehow getting the key? I'm going to check with the xfce guys as well, but in the meantime hopefully some discussion can happen =]

**Comment by Deltafire** [comment]
This is a common problem with various window managers.  Best to map the Windows/OSX/Whatever modifier key for the window manager shortcuts and leave CTRL/ALT for applications, if possible.

I think it's an xfce bug if it's trapping the key and also sending it to the application.
