### ISSUE TITLE
API Key in travis.yml

### ISSUE THREAD

**Issue by MBeijer** [milkytracker/MilkyTracker#185]
Is it really wise to keep the api key in the travis.yml file?

**Comment by dwhinham** [comment]
This is not a usable plaintext key, it is encrpyted.

See: https://docs.travis-ci.com/user/encryption-keys/

**Comment by MBeijer** [comment]
Thanks for clarification! I thought it looked like a potential security risk, so better safe than sorry. :)

**Comment by dwhinham** [comment]
Thanks for the concern either way! :smiley:
