### ISSUE TITLE
32-bit Milkytracker binary not supported in 10.15 Catalina

### ISSUE THREAD

**Issue by VirtualDisk** [milkytracker/MilkyTracker#189]
Currently this app does not launch in 10.15, as Apple has discontinued support for 32-bit apps. See screenshot. 
<img width="414" alt="Screen Shot 2019-10-14 at 3 53 41 PM" src="https://user-images.githubusercontent.com/15205414/66778845-d5bfc580-ee9a-11e9-836d-7afcbaf32079.png">

**Comment by Deltafire** [comment]
I cannot confirm this issue.  The 1.02 release is working as expected on my 10.15 Catalina macbook.
