### ISSUE TITLE
emscripten build error

### ISSUE THREAD

**Issue by netpipe** [milkytracker/MilkyTracker#190]
typedef unsigned char     uint8_t;
typedef unsigned short    uint16_t;
typedef unsigned int      uint32_t;
typedef unsigned long int uint64_t;

after adding the above to the BasicTypes.h file  it came to

error: static_assert failed due to requirement '__builtin_offsetof(__wasi_dirent_t, d_ino) == 8' "non-wasi data layout"

during compile

**Comment by dwhinham** [comment]
This is not a valid bug report, we make no claims of support for emscripten.

The application needs significant porting work to be done to able to run on emscripten, it's unfortunately not just a case of some typedefs and a compile.
