### ISSUE TITLE
fatal error: SDL.h: No such file or directory

### ISSUE THREAD

**Issue by 2pxsolidblack** [milkytracker/MilkyTracker#194]
MilkyTracker is no longer buildable on my Arch linux system. I got this error:

```
[ 15%] Building CXX object src/milkyplay/CMakeFiles/milkyplay.dir/AudioDriverManager.cpp.o
In file included from /home/carloratm/w/MilkyTracker/src/milkyplay/AudioDriverManager.cpp:148:
/home/carloratm/w/MilkyTracker/src/milkyplay/drivers/sdl/AudioDriver_SDL.h:40:10: fatal error: SDL.h: No such file or directory
   40 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [src/milkyplay/CMakeFiles/milkyplay.dir/build.make:76: src/milkyplay/CMakeFiles/milkyplay.dir/AudioDriverManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:342: src/milkyplay/CMakeFiles/milkyplay.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

I tried reverting to 3e13e4136a3f88cd0f94ce2e35080d38381e0847 and it works fine.
I suspect the problem is with this 87d0f55cd8868d91472f96cccafaf6fdb9e0cbbc
but unfortunately I can't help finding a solution, other than testing.

**Comment by dwhinham** [comment]
Thanks for reporting.

It looks like Arch Linux builds their SDL2 package with CMake (other distros use autotools) and they use the newer CMake way of exporting include directories and link libraries.

Fixing this will need some care as to not break distros that still do things the original way.
I'll work on this ASAP.

**Comment by dwhinham** [comment]
@2pxsolidblack 

I've just done a large update to the CMake scripts throughout the whole project.
As part of this, Arch Linux users should hopefully now be able to build without any problems.

Would you mind pulling 2b145b074581ddf3b4ad78a402cdf5fab500b125 (the `cmake-update` branch) and giving it a try?

I've tested building this branch in:

- Arch Linux (current)
- Fedora 31
- Ubuntu 18.04 LTS
- FreeBSD 11
- macOS (via. CI only)
- Windows (Visual Studio 2019)

**Comment by 2pxsolidblack** [comment]
@dwhinham 

works like a charm, on an up to date Arch Linux.

Thanks for that!

**Comment by dwhinham** [comment]
Thanks for testing!

I'll merge this into master and call it closed.

If anyone else encounters build issues on other distributions, feel free to open a new issue.
