### ISSUE TITLE
UI issue: sample generators (sine, sawtooth, ...) can not be used to generate 1/4 period waveform

### ISSUE THREAD

**Issue by CorvusCorax** [milkytracker/MilkyTracker#205]
The UI dialog for the sample generators limits the number of period from 0.0f to 1000.0f with only one digit behind the decimal point.

For some applications (creating envelopes for filters) entering half (0.5) or quarter (0.25) periods is useful, for example to create a smooth ramp. Unfortunately 0.25 is not a valid entry.

The max value of 1000 is also arbitrary. Sensible maximum would be 1/2 the sample length, filling the entire sample with a waveform of maximum (Nyquist) frequency.

Both are addressed in https://github.com/milkytracker/MilkyTracker/pull/204

740098ecf72bd303b12461bf5f192507fce45575

cheers :)

**Comment by Deltafire** [comment]
#204 merged.
