### ISSUE TITLE
Wayland support/touch support

### ISSUE THREAD

**Issue by TheMorc** [milkytracker/MilkyTracker#209]
Hi, i want to know if there's a simple way to implement touch support or even support for Wayland.
I actually compiled it for Sailfish OS and it actually works, but without touch or orientation

**Comment by Deltafire** [comment]
Touch is already supported via mouse emulation, it should "just work".  There isn't any gesture support however.

Wayland is supported if libsdl2 supports it.

**Comment by TheMorc** [comment]
Oh right, so orientation isn't making much of a problem (portrait resolution or just rotating it with argument works just fine), so only the touch doesn't seem to work. I actually tried on two devices. So is there something in the code so i could "attach" to it and monitor SDL mouse events or i have to try something else?

**Comment by TheMorc** [comment]
Small update, i found out that SDL_MOUSEBUTTONDOWN and SDL_MOUSEBUTTONUP events aren't even getting registered after touching the screen. I tried changing it to SDL_FINGERDOWN  from SDL_TouchFingerEvent and it compiled, started, and after touching i think that it actually did register as it crashed right away.
