### ISSUE TITLE
Support for others instruments format.

### ISSUE THREAD

**Issue by Speedvicio** [milkytracker/MilkyTracker#212]
it would be great to be able to import others instruments format like, brr or tfi.

**Comment by dwhinham** [comment]
.TFI has already been [discussed here](https://modarchive.org/forums/index.php?topic=3401.0) - we can't just "import" an FM format synth instrument, we'd have to have a synth engine to render it out, which is way beyond the scope of a sample-based tracker.

We'd probably be open to a pull request for a BRR converter, but it likely won't be from us; you can just convert the .BRR to .WAV with say, https://github.com/nyanpasu64/BRRtools, and load it in.
