### ISSUE TITLE
ALSA lib pcm.c:8594:(snd_pcm_set_params) Access type not available for PLAYBACK: Invalid argument

### ISSUE THREAD

**Issue by freddieventura** [milkytracker/MilkyTracker#214]
Hi , Thanks a lot for this powerful tool , is great and I'm looking forward doing so much tunes with it so I can't wait to use it.
I just have a couple of issues:
First off my specs are:
```
Kali linux (Debian Buster)
Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
Milkytracker v1 .02.00 (The one available on github downloaded today)
```
When I first initiate *milkytracker* it doesnt detect nor **ALSA** Drivers nor **JACK** drivers so I have to go with SDLaudio: Using audio driver: pulseaudio (which as far as I know is not the bestone, its been said that ALSA handles processes more efficiently)

So if I try to switch to **ALSA** I get this message:
`ALSA lib pcm.c:8594:(snd_pcm_set_params) Access type not available for PLAYBACK: Invalid argument`

Then my only option is working with ** pulseaudio** but when I use this the program crashes sometimes unexpectedly crashing the whole computer (mainly when I use milkytracker along other stuff which requires audio access such as (*youtube*).

I'm not able to troubleshoot this lastone issue but, I would like to be able to use *ALSA* which I believe it may solve the problem.
Do you have any idea on what I'm doing wrong?

Thanks

**Comment by dwhinham** [comment]
Hi there,

Have you tried other samplerates (Mixer Resolution in the audio options) and buffer sizes when trying ALSA?

Are you able to get basic ALSA audio playback using `aplay` on the command line?
When using ALSA are you sure PulseAudio hasn't hogged the ALSA device? You can use `pulseaudio --kill` to ensure it's not running.
