### ISSUE TITLE
Key velocity not work

### ISSUE THREAD

**Issue by sthanduther** [milkytracker/MilkyTracker#231]
I have a keyboard (MIDI controller) with velocity feature. In concurrent Impulse Tracker clone this feature works prety good. But in Milkytracker this not work. The volume value is _40_ something. Why?

Arch Linux.

**Comment by SyntaxErrol** [comment]
On windows at least, velocity sensitive has to be enabled separately:
![image](https://user-images.githubusercontent.com/3283914/106562441-f8b03600-6532-11eb-8ff3-b8ecb2b1ea93.png)

**Comment by sthanduther** [comment]
In Linux (with Jack) this feature is enabled for default. Just in Milkytracker this feature not work.

**Comment by sthanduther** [comment]
Ok. Problem solved.

In terminal, just type _milkytracker -recvelocity_.

**Comment by minidcon7** [comment]
> Ok. Problem solved.
> 
> In terminal, just type _milkytracker -recvelocity_.

Is there a GUI button for that option?
