### ISSUE TITLE
Layout > Resolutions > Scale is greyed out

### ISSUE THREAD

**Issue by applebait** [milkytracker/MilkyTracker#232]
I'm on Big Sur and I can't find a way to enable the Scale buttons under Config/Layout/Resolutions.
TiA

**Comment by Deltafire** [comment]
Scaling isn't supported on MacOS/Cocoa.

You can obtain a simiar affect by resizing the window using a corner drag handle.

**Comment by applebait** [comment]
Yes, I know but then the fonts get a bad render. I noticed that in Mojave we can multiply but not in Big Sur, so it's not an macOS, per se, limitation but thanks for the insight.

**Comment by Deltafire** [comment]
It's grayed out in Catlina, looking at the code it doesn't seem to be an option for the OpenGL render which the mac port uses.

Your options would be to either build the SDL version, use the older Carbon version of MilkyTracker or modify the OpenGL render code.

**Comment by Agrrox** [comment]
I'm having scaling issue on macos high sierra on 1.03
