### ISSUE TITLE
Makeicns fails on macOS Big Sur

### ISSUE THREAD

**Issue by martinmosegaard** [milkytracker/MilkyTracker#234]
OS: macOS Big Sur 11.2.3

Steps to reproduce:
Run build_macos.sh.
It downloads docerator which contains a makeicns executable, which is called from `resources/pictures/docicons/osx/genicons.py`.
Running that gives an error:
```
resources/pictures/docicons/osx/docerator (master) $ ./makeicns
-bash: ./makeicns: Bad CPU type in executable
```

I am able to build using this repo: https://github.com/GitableRoy/MakeICNS
and updating the path in the python script to the shell script in that project:
```
MAKEICNS_PATH = "../../../../../MakeICNS/makeicns.sh"
```
(It also requires `magick` which can be installed with `brew install imagemagick`.)

I also tried https://formulae.brew.sh/formula/makeicns but it fails to install:
```
$ brew install makeicns
Error: makeicns has been disabled because it has a removed upstream repository!
```

I don't know makeicns so I am not sure what the best solution is. Docerator also seems a bit old.

**Comment by Deltafire** [comment]
Docicons generation now removed in rc1.05 due to unmaintained Docerator.
