### ISSUE TITLE
Generate more waveforms

### ISSUE THREAD

**Issue by cxong** [milkytracker/MilkyTracker#239]
Under sample editor, Generators > ..., add more options for waveforms

I'm mostly interested in OPL waveforms like (https://doomwiki.org/wiki/OPL_emulation)

- Half sine
- Absolute sine
- Quarter sine
- Alternating sine
- Camel sine
- Logarithmic sawtooth

**Comment by coderofsalvation** [comment]
this is being fixed by the upcoming embedded synth
