### ISSUE TITLE
Crash when replen reduced to 4

### ISSUE THREAD

**Issue by Deltafire** [milkytracker/MilkyTracker#25]
Original bug report:

http://modarchive.org/forums/index.php?topic=1357.0

Confirmed on Windows 64-bit.

**Comment by Deltafire** [comment]
Well, I thought it was confirmed.. I am no longer able to reproduce this bug.

**Comment by CorvusCorax** [comment]
I tried to reproduce this bug on 64bit Ubuntu. Can't reproduce it with 1.0.0.

**Comment by Deltafire** [comment]
Still can't reproduce this on Windows x64 or OSX. Closing for now.
