### ISSUE TITLE
[feature] playlist

### ISSUE THREAD

**Issue by cederom** [milkytracker/MilkyTracker#257]
Thank you for this marvelous program! I am using it with success on FreeBSD :-)

It would be nice to have Playlist feature in MilkyTracker so it plays all tunes from a given directory. Watching tracks is kind of cool fat better than other players :-)

Thank you for considering :-)

**Comment by coderofsalvation** [comment]
ocp (opencubic player) might be better for this (but thanks for suggesting!).
It is indeed fun to watch!

**Comment by cederom** [comment]
BIG TANKS for the hint on OCP @coderofsalvation ! :-)

There is a port for FreeBSD and it works out of the box like a charm with so many formats supported! :-)
