### ISSUE TITLE
[Req] Binaries for AmigaOS (WB 3.1 or higher on 68k)

### ISSUE THREAD

**Issue by ajack2001my** [milkytracker/MilkyTracker#265]
Can somebody please compile the source for the above platform for users that don't have a dev environment on our Amigas?

**Comment by ajack2001my** [comment]
Nobody? :'(

**Comment by caseyjoy** [comment]
Unfortunately, the main milkytracker/MilkyTracker build doesn't do builds for Amiga (I suspect it's probably missing some things that would be important for making that work properly).

You might have better luck on the [Amiga specific AmigaPorts/MilkyTracker fork](https://github.com/AmigaPorts/MilkyTracker).

While not quite as recent, one of the builds found there might still do what you're looking for - or at the very least you'd be more likely to find someone who knows how to do an Amiga build.

**Comment by coderofsalvation** [comment]
in case somebody does an amiga build, please let them post a link to a binary in this thread. thx

**Comment by Deltafire** [comment]
From the AmigaPorts repo linked above (now updated to 1.03):

https://dl.amigadev.com/nightly/milkytracker/
