### ISSUE TITLE
need infos about license for a new fork

### ISSUE THREAD

**Issue by gibs75** [milkytracker/MilkyTracker#269]
Hi,
I have developed a sound replay routine specific for Atari STe starting from scratch working with the specific hardware limitations (1st version of the routine is published here https://github.com/gibs75/demOS). 
It has very strong contraints and I have made a fork of Milkytracker to allow to compose for this very specific routine. I would like to be able to share this work with the community at one point (even if this is a very special / dedicated fork).

My questions : 
- are there specific constraints to follow about licensing ?
- what kind of license should be used for sources files added to milkyplay project ? permissive license (MIT, open BSD) ? can it be GPL ? (from what I have seen only higher level milkytracker project is GPL)

Thanks

Best regards

J.H

**Comment by Deltafire** [comment]
The replayer is BSD and the rest of the tracker GPL. See the file COPYING for details.Sent from my Galaxy
-------- Original message --------From: gibs75 ***@***.***> Date: 06/02/2022  21:06  (GMT+00:00) To: milkytracker/MilkyTracker ***@***.***> Cc: Subscribed ***@***.***> Subject: [milkytracker/MilkyTracker] need infos about license for a new fork (Issue #269) 
Hi,
I have developed a sound replay routine specific for Atari STe starting from scratch working with the specific hardware limitations (1st version of the routine is published here https://github.com/gibs75/demOS).
It has very strong contraints and I have made a fork of Milkytracker to allow to compose for this very specific routine. I would like to be able to share this work with the community at one point (even if this is a very special / dedicated fork).
My questions :

are there specific constraints to follow about licensing ?
what kind of license should be used for sources files added to milkyplay project ? permissive license (MIT, open BSD) ? can it be GPL ? (from what I have seen only higher level milkytracker project is GPL)

Thanks
Best regards
J.H

**Comment by coderofsalvation** [comment]
@gibs75 yes, I don't see any problems with your approach.
