### ISSUE TITLE
Apple Silicon (arm64-apple-darwin) v1.03.00 release build

### ISSUE THREAD

**Issue by h0gan1ee** [milkytracker/MilkyTracker#270]
I make a macOS build on my M1 machine and here it is, in case anyone needs it.

[milkytracker-1.03.00-darwin-arm64.dmg.zip](https://github.com/milkytracker/MilkyTracker/files/8059319/milkytracker-1.03.00-darwin-arm64.dmg.zip)

<img width="1099" alt="Screen Shot" src="https://user-images.githubusercontent.com/39949564/153832569-47dffa6e-eeab-4847-b105-0f6637d458b4.png">

**Comment by h0gan1ee** [comment]
#248

**Comment by Deltafire** [comment]
Added to the releases page, thank you!

**Comment by shayneoneill** [comment]
Is there a version of this that works? The supplied one above says its "damaged"

**Comment by h0gan1ee** [comment]
> Is there a version of this that works? The supplied one above says its "damaged"

That's because neither the image or the application is notarized by Apple, so Gatekeeper will stop you from running it.

Here's a workaround: https://www.howtogeek.com/205393/gatekeeper-101-why-your-mac-only-allows-apple-approved-software-by-default/

**Comment by thebillington** [comment]
+1 for the above solution from `andruby`
