### ISSUE TITLE
MilkyTracker crashes with exception code 0xe06d7363 when I put my Windows 10 laptop into sleep mode

### ISSUE THREAD

**Issue by ghost** [milkytracker/MilkyTracker#280]
I have an HP laptop running Windows 10 21H2. This error happens for both v1.03.00 and the latest unstable version of MilkyTracker. It only happens for builds compiled with submodules (lhasa, rtaudio, zlib, and zziplib.)

When I run MilkyTracker and put my laptop into sleep mode, then when I turn it back on, I get an error saying that MilkyTracker has crashed. When I check the Event Viewer, I see that this event is logged each time it crashes:
```
Log Name:      Application
Source:        Application Error
Date:          7/16/2022 6:46:14 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-2VRNB8D
Description:
Faulting application name: MilkyTracker.exe, version: 0.0.0.0, time stamp: 0x62d32158
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1826, time stamp: 0x299341e8
Exception code: 0xe06d7363
Fault offset: 0x0000000000034fd9
Faulting process id: 0x1200
Faulting application start time: 0x01d8996d0d885fce
Faulting application path: C:\Users\Gibbon Monke\Documents\Programs\MilkyTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 999bb96d-dd59-48af-a2b8-9a15330ca7cd
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-16T23:46:14.3806546Z" />
    <EventRecordID>11874</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-2VRNB8D</Computer>
    <Security />
  </System>
  <EventData>
    <Data>MilkyTracker.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>62d32158</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1826</Data>
    <Data>299341e8</Data>
    <Data>e06d7363</Data>
    <Data>0000000000034fd9</Data>
    <Data>1200</Data>
    <Data>01d8996d0d885fce</Data>
    <Data>C:\Users\Gibbon Monke\Documents\Programs\MilkyTracker.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>999bb96d-dd59-48af-a2b8-9a15330ca7cd</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```
So, MilkyTracker is crashing with exception code `0xe06d7363`, and it has something to do with `KERNELBASE.dll`. I don't know if this is an issue with my system or a bug with MilkyTracker. I have tried running `DISM /Online /Cleanup-Image /ScanHealth; DISM /Online /Cleanup-Image /CheckHealth; DISM /Online /Cleanup-Image /RestoreHealth; sfc /scannow`, but this did not fix the problem.

**Comment by Code-Marmoset** [comment]
So, I used the Visual Studio debugger, and it seems that the error is related to RtAudio. The error string given is `RtApiWasapi::wasapiThread: Unable to retrieve render buffer size.` Setting the audio driver to WaveOut fixes it, but if I set it to any of the RtAudio drivers, the crashes come back.

**Comment by Code-Marmoset** [comment]
So, I went into the Visual Studio debugger, and the error is coming from RtAudio. The error string given is `RtApiWasapi::wasapiThread: Unable to retrieve render buffer size.` Setting the audio driver to WaveOut fixes the issue, but using any of the RtAudio drivers makes the crashes come back.

**Comment by coderofsalvation** [comment]
interesting, thx for reporting.
I have similar issues on my linux machine, but it doesn't crash (it just doesn't produce audio anymore).
There might be something fishy going on with RtAudio (no idea whether its on a milkytracker or RtAudio-level though).

**Comment by johanhelsing** [comment]
I also get a crash on windows 11 when resuming from sleep.

**Comment by coderofsalvation** [comment]
windows/linux users can you check if this is still the case with v1.04 ? see milkytracker.org/downloads
