### ISSUE TITLE
Milkytracker black screen on Nvidia gpu Linux with SDL 2.24.0

### ISSUE THREAD

**Issue by mward25** [milkytracker/MilkyTracker#295]
Output from milkytracker:
```
Available Renderers: opengl opengles2 software 
Vendor     : NVIDIA Corporation
Renderer   : NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Version    : OpenGL ES 3.2 NVIDIA 515.65.01
SDL: Minimum window size set to 640x480.
SDL: Using accelerated renderer.
SDL: Renderer supports rendering to texture.
SDL: Using audio driver: pulseaudio
SDL: Buffer size = 2048 samples (requested 2048)
```

Does not work with SDL2 2.24.0,
but it does work with SDL2 2.0.22.

Here is the thread I created on the arch linux forums (in case that helps):
    https://bbs.archlinux.org/viewtopic.php?pid=2056385#p2056385

**Comment by yves-le-berre** [comment]
I just opened issue #6271 to libsdl-org/SDL.

**Comment by Deltafire** [comment]
Have you tried resizing the window? I've seen something similar in the past where resizing the window made the contents appear.

**Comment by yves-le-berre** [comment]
The window can only have a size superior to the minimum windows size given in configuration (mine is 1440x900) and if i enlarge the window (i can do it because my screen is 1920x1080), it stays black. This has also the curious effect to disable the WM close window button (and corresponding menu item)

**Comment by yves-le-berre** [comment]
No more black window with milkytracker 1.03.00 and sdl2-git 2.24.0.r289.g8d2cb1555.

**Comment by mward25** [comment]
Given this new information, should I close this issue?

**Comment by yves-le-berre** [comment]
Yes, this behavior is due to SDL.
sdl2 release planned end of next month.

**Comment by josephbburg** [comment]
I am having this issue when I try to build - is it possible to choose a different renderer in the meantime?
Here's what I get in the console.
`Available Renderers: opengl opengles2 software`
But how to choose one or the other?
