### ISSUE TITLE
Midi Input Crashes MilkyTracker: Mac OS 12 Native M1

### ISSUE THREAD

**Issue by tadashibashi** [milkytracker/MilkyTracker#297]
I'm using the arm64 version of MilkyTracker from the releases page on my MacOS 12, Apple Silicon M1 machine. 
There are two issues that I'm not sure are related or not:
1. The preferences menu is grayed out, so I can't access any MIDI settings.

2. When I activate record, and input MIDI notes from my controller, sometimes MilkyTracker will crash entirely. Other times, nothing happens until you click on the interface, and then the notes appears.

**Comment by peterbart-lmi** [comment]
I have an M1 Mac, I can check this maybe, but I don't have a MIDI controller. Is it possible you provide a crash dump of the crash? You can get it from the console application under crashes.
