### ISSUE TITLE
Cant reset settings

### ISSUE THREAD

**Issue by Krocodile55** [milkytracker/MilkyTracker#298]
so I was trying to get started with milkytracker and the first thing I did was go to settings because I could barely make anything out, now I'm stuck with pixels that are too large and I cant find the "appdata" folder even though i am using windows. 
was there some kind of installation thing i missed?

**Comment by bratpeki** [comment]
Your description is very fragmented. If you want to reset MilkyTracker, you have to delete a file named `config`. It is located in a folder called `milkytracker`. I am on Linux, so I can't tell you the exact location, but I am sure of the fact that your file hierarchy should look like how I wrote above. You can always use a program like [Everything](https://www.voidtools.com/) to find the exact location, if you're struggling with that.

**Comment by coderofsalvation** [comment]
usually something like `C:\Users\yourusername\AppData\milkytracker`
