### ISSUE TITLE
mac build wanted for v1.04

### ISSUE THREAD

**Issue by coderofsalvation** [milkytracker/MilkyTracker#315]
can somebody provide/compile binaries (any macos version welcome) which we can attach to the latest release? ❤️
(@peterbart-lmi ?)

```
$ git clone git@github.com:milkytracker/MilkyTracker.git
$ cd MilkyTracker
$ git reset --hard 1fa39ca     # v1.04 release
$ ./build_macos.sh
```

**Comment by johngirvin** [comment]
I have a milkytracker-1.04.00-Darwin.dmg built with the script above.

**Comment by peterbart-lmi** [comment]
> I have a milkytracker-1.04.00-Darwin.dmg built with the script above. Let me know how I can get it to you.

You were fast ☺️

**Comment by coderofsalvation** [comment]
awesome! thank you very much!

> Could you be so kind to upload it to https://filebin.net/ and post the link here?

I will then attach it to the current release

**Comment by johngirvin** [comment]
https://filebin.net/vs4n20wtx6plbfui

Built on macOS 12.6.7 x86
XCode 14.2 installed

**Comment by coderofsalvation** [comment]
thank you! x86 means 32bit right? 
So if somebody else could provide a 64bit, that'd be great

**Comment by johngirvin** [comment]
Sorry, x64, it's a 64-bit build.

**Comment by peterbart-lmi** [comment]
Xcode no longer supports building 32 bit Intel binaries for macOS. But then again, having a universal or an arm64 build, that would be nice 😉

**Comment by peterbart-lmi** [comment]
@coderofsalvation the first channel scope background is grey, is that a new feature or did a find a bug?

![Bildschirmfoto 2023-07-05 um 15 50 54](https://github.com/milkytracker/MilkyTracker/assets/69579956/bc2900dc-4e7f-4972-9eee-dd0416e7aa9d)

**Comment by krehel** [comment]
@coderofsalvation - Filebin seems to be restricting uploads due to over capacity.  Do you have another preferred file service?  Else I can upload to GoFile or an alternate service.

**Comment by coderofsalvation** [comment]
GoFile is also fine, it's just temporary so I can download it

**Comment by krehel** [comment]
https://gofile.io/d/frcI7C

I'll also take care of updating the macOS Homebrew cask once both versions are posted.

**Comment by coderofsalvation** [comment]
Thanks to you @krehel @johngirvin for empowering other mac users ❤

**Comment by krehel** [comment]
@coderofsalvation - I am really sorry!  The arm64 build may cause issues for users as macOS may report the software as damaged due to not being signed/notarized due to policy.  How do you want to handle this?  I suppose I could do those steps, but since I'm not a part of your team I am not sure that is appropriate or desired.

Calling this out now before any issues may start to get opened.  I didn't notice this because my local build copy worked, and the GitHub download did not despite being the same sha256.

I had to run `xattr -d com.apple.quarantine /Applications/Milkytracker.app` in order to get it opened.

**Comment by johngirvin** [comment]
Same, let me know what you need to do for the x86_64 build.

**Comment by peterbart-lmi** [comment]
Well, for macOS I guess somebody "official" would need to register an official Apple developer account which we can use to sign the binaries, so they can be run without any restrictions. Unfortunately the membership is not free, I believe it's $99 per year.

**Comment by johngirvin** [comment]
`xattr -d com.apple.quarantine /Applications/Milkytracker.app` also works for x86_64.

**Comment by coderofsalvation** [comment]
thanks (updated docs)

**Comment by krehel** [comment]
I spent some time yesterday trying to figure this out and I was able to ad-hoc sign the binary.  Working in CMake and all this is not my strong suit. 😃  

But, signing can be done without an official Apple developer account and spending the $99.

I'm going to keep working on this a bit more to make sure what is being produced will work.

Apologies for the extra overhead and hassle.

**Comment by krehel** [comment]
@coderofsalvation - I added you to a private repository for the signed ARM build.  Figured it might be better than scattering files across services.  I set a release with the latest file I built.

**Comment by peterbart-lmi** [comment]
Yes, ad-hoc signing is possible, but IMO not the recommended way for software that is to be released:
https://apple.stackexchange.com/a/317002

**Comment by mlaves** [comment]
Hi, I also created a build on macOS 14.1 Sonoma on Apple silicon and my binary does not require to call `xattr ...`. Tested that by running the app on a different machine with a fresh install of macOS 12.6:

https://filebin.net/vypu4yq3eqgu2khi/milkytracker-1.04.00-Darwin.dmg

I used the following commands to build the app
```bash
git checkout v1.04.00
cmake -S . -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -GNinja -DCMAKE_BUILD_TYPE=Release
cmake --build build --target package
```

**Comment by coderofsalvation** [comment]
anyone in this issue, please consider doing the same magic for the latest release: https://github.com/milkytracker/MilkyTracker/issues/341
