### ISSUE TITLE
MIDI support no longer optional

### ISSUE THREAD

**Issue by Deltafire** [milkytracker/MilkyTracker#332]
Logged via IRC:

`<plasma41>` MIDI support in milkytracker was mistakenly made non-optional by commit f578adfa333ea52c84654acf08d6024ae76c10fd. The addition of the REQUIRED keyword of the find_package() command results in the 'else' codepath in the following 'if' conditional never being reached.

**Comment by coderofsalvation** [comment]
```
find_package(RTMIDI "2.1.0" REQUIRED) # 2.1.0 and above
```
OK I guess REQUIRED does not mean '2.1.0' and above.
Should look up the CMAKE docs to do this properly.

**Comment by Deltafire** [comment]
Fixed in https://github.com/milkytracker/MilkyTracker/commit/50273e401024a9ece4bcb095f650d1efaa628bf4
