### ISSUE TITLE
MilkyTracker inhibits screensaver/monitor sleep while running

### ISSUE THREAD

**Issue by eevee** [milkytracker/MilkyTracker#339]
This is [SDL2's default behavior](https://wiki.libsdl.org/SDL2/SDL_DisableScreenSaver), presumably because SDL is mainly intended for games, but it doesn't seem intentional for creative software that might reasonably be left running in the background.  Certainly confused the hell out of me until I figured out Milky was the culprit  :)

**Comment by coderofsalvation** [comment]
thanks for reporting.
So the suggestion is calling `SDL_DisableScreenSaver(void)` during startup?

**Comment by coderofsalvation** [comment]
I'm not sure how SDL_EnableScreenSaver (in the PR) is going to fix this (I've added a comment to the PR)
