### ISSUE TITLE
Can we have an option for odd channel numbers at least?

### ISSUE THREAD

**Issue by Hundredlegger** [milkytracker/MilkyTracker#343]
I still believe that someday, true IT compatibility will come, but in the meantime, is there a way to select whenever "add" or "sub" will add or sub a different number of channels?

Like, make it in the settings so that you can change if it will add or sub "1", "2" or "4" channels at a time.

I mean, we kinda already did this with how many XM channels are allowed, like "32", "64" or "128", so why not with the number of channels you can add or sub?

(Also, is there a setting somewhere that allows you to switch between fine volume control like "h100/256 to 0" to hard volume control like the original Fasstracker II does "h40/64 to 0"?)

**Comment by Hundredlegger** [comment]
@coderofsalvation I'm referring to how Fasttracker 2's envelope can only be in y0 to y64, as in, there are only 64 steps in the y direction. In Milkytracker, I noticed that it is y0 to y256, meaning that there are 256 steps in the vertical direction.

As for the channel thing, I just think it would be the least controversial change, since it doesn't tamper with anything that could potentially introduce new bugs to the player.

**Comment by Hundredlegger** [comment]
@coderofsalvation Is there an option to turn it off? Having 256 steps is nice, but it is not nice when I have to be forced to use it.

Also, the KiSS principle is pretty stupid. Impulse Tracker has the simplest mechanic, since it has all channels available and whichever one you didn't use is trimmed from the file you saved. If you still want the ability to manually choose how many channels you have, the simplest implementation is to have a button where you can input a number to choose how many channels you want.

**Comment by coderofsalvation** [comment]
Ah ok, so you mean a textfield input (this was not clear before).
I think the brainstorm is an important one to have, but it's still vague (where to show and trigger the textfield)
Unfortunately I don't have the bandwidth to experiment with it right now.
Maybe you can create a more detailed userstory, and find another maintainer/dev to do a PR for it.
