### ISSUE TITLE
MilkyTrackerX build Discord link has expired

### ISSUE THREAD

**Issue by esaruoho** [milkytracker/MilkyTracker#352]
<img width="602" alt="Screenshot 2024-08-15 at 0 04 39" src="https://github.com/user-attachments/assets/c49f28e1-4aa7-4bed-bc33-09754048af12">

**Comment by Nine-H** [comment]
I was also wondering about this...

**Comment by coderofsalvation** [comment]
https://discord.gg/y3jaR43kmg  <-- updated

**Comment by esaruoho** [comment]
thank you
