### ISSUE TITLE
macOS icon in dmg misplaced

### ISSUE THREAD

**Issue by sacredbanana** [milkytracker/MilkyTracker#355]
Unsure if the intel version also is like this but I got confused when I opened the .dmg for the apple silicon version because the icon was not in the right place. The arrow means nothing like this

<img width="941" alt="image" src="https://github.com/user-attachments/assets/c47d173e-1690-4c8b-90f5-15cec62293c0">

**Comment by Deltafire** [comment]
This has been fixed in fd29dae (on RC/1.05 branch).
