### ISSUE TITLE
Check boxes: Allow section from label

### ISSUE THREAD

**Issue by Deltafire** [milkytracker/MilkyTracker#54]
16:18 <eightbitbubsy> also another annoying thing (not a bug) is that check boxes can only be activated by clicking the boxes themselves, not the text next to it (like FT2 and all common-sense GUIs)

**Comment by hisojarvi** [comment]
I started working on this, and I have a working implementation here:
https://github.com/hisojarvi/MilkyTracker/commit/04d37e220207115d690a4721cb18c74ef0e5ab71
The biggest task will be to go through the whole UI and convert static labels into clickable checkbox labels where appropriate. I would appreciate if one of the core contributors (@Deltafire or @dwhinham ?) could take a look at what I did so far and give a thumbs up before I go ahead.

**Comment by hisojarvi** [comment]
@Deltafire I fixed the build error in this commit: https://github.com/hisojarvi/MilkyTracker/commit/6aa366ed5d29920a0ecf5b88ba7b7b6eadb55e4c

Let me know if you're ok with this approach, and then I can convert also the other checkbox labels into clickable ones.

**Comment by hisojarvi** [comment]
Clickable check box labels are available in this PR: #93

**Comment by Deltafire** [comment]
Merged.. Thanks for the patch :)
