### ISSUE TITLE
Official Website down?

### ISSUE THREAD

**Issue by borrougagnou** [milkytracker/MilkyTracker#55]
The website http://milkytracker.org/ is down :/ impossible download MilkyTracker :/

**Comment by Deltafire** [comment]
Unfortunately we don't have control of the milkytracker.org domain and the owner is unwilling to cooperate at this time.

We are looking into options to resolve this issue.

**Comment by dwhinham** [comment]
All sorted :)

MilkyTracker is now hosted at GitHub Pages, and TiTAN have given us a new subdomain.

MilkyTracker's new home is at: http://milkytracker.titandemo.org
