### ISSUE TITLE
having trouble installing 

### ISSUE THREAD

**Issue by lexoyo** [milkytracker/MilkyTracker#56]
Hello
I am trying to install Milky on fedora, and as I understood I try to build the source
For that I need to create the ./configure file with something like `AM_PATH_ALSA=/usr/bin/ autoconf` (am I correct? it is not said in the README nor INSTALL files)
If I do so `AM_PATH_ALSA=/usr/bin/ autoconf && ./configure` I get this error:
```
./configure: line 2405: syntax error near unexpected token `dist-bzip2'
./configure: line 2405: `AM_INIT_AUTOMAKE(dist-bzip2 subdir-objects)'
```
Do you know where it comes from? Am I on the right track?
Thank you!

**Comment by Deltafire** [comment]
From the README:

If you have obtained the MilkyTracker sources from the version control
repository, the autotools generated files (INSTALL, configure, etc) will
be missing. To obtain these either generate them using 'autoreconf -i'
(requires autoconf/automake to be installed) or obtain them from the
release package.

Note that the autoconf build has now been dropped in favour of cmake, see the 'pending' branch.

**Comment by lexoyo** [comment]
woops ok, sorry about that
and thank you!!
