### ISSUE TITLE
Songs opened as a cmd line argument are saved to a different directory

### ISSUE THREAD

**Issue by Deltafire** [milkytracker/MilkyTracker#57]
22:32 \<zoner\> I don't know if this is a known bug or what, but if you supply a filename at the command line that's not a full path, then subsequently the song gets saved at the last place that milkytracker has changed directories (in file browser, instrument and sample chooser, etc)
22:32 \<zoner\> it gave me a near heart attack when it looked like a few hours of work had just vanished
22:32 \<zoner\> but it was instead just saved someplace deep in a directory structure where i have samples
22:33 \<zoner\> so now i just don't trust passing a file name on the command line at all
22:33 \<eightbitbubsy\> shouldn't it always save to the current working directory?
22:34 \<eightbitbubsy\> (I don't know how it works though :D)
22:34 \<eightbitbubsy\> e.g. the directory that is open in disk op.
22:35 \<zoner\> like, you do $ milkytracker mysong.xm
22:35 \<zoner\> then you go look for a new sample bongas.wav with the sample chooser thing
22:35 \<zoner\> and here you are changing directoies
22:36 \<zoner\> then when you save it'll save the file "current-directory/bongas.wav"
22:36 \<zoner\> errr
22:36 \<zoner\> sorry
22:36 \<zoner\> current-directory/mysong.xm
22:36 \<zoner\> not directory-where-mysongxm-is/mysong.xm
22:37 \<zoner\> because it probably just saves "mysong.xm" but now you're in the directory that your bongas are in
22:37 \<zoner\> whereas in all other cases, it is a full path
22:39 \<zoner\> solving this i think means either not changing current directory ever, or somehow making sure the command line argument is converted to its full path version of itself during argument parsing

**Comment by farvardin** [comment]
yeah, it sounds like a bug, because it's an unexpected behavior!
