### ISSUE TITLE
Horizontal scroll wont reset in instrument/samples fields when name shortened

### ISSUE THREAD

**Issue by S-ed** [milkytracker/MilkyTracker#59]
Problem:
- There's a name of the instrument is long enough to horizontal scroll bar to appear
- Edit name so it could fit the window, that will cause the scrollbar to disappear
- But if scrollbar was shifted window will remain it's shift

Temporary solution:
- In edit mode still possible to navigate to the beginning of the line so it will scroll back.

![milkytracker](https://cloud.githubusercontent.com/assets/3008353/22182728/b550091a-e0bd-11e6-83ab-0afacd33e766.gif)

**Comment by Deltafire** [comment]
Great bug report, thanks!

**Comment by S-ed** [comment]
@Deltafire
You're welcome. It's actually first time someone tells me that bug report is "great".
Great software!

**Comment by Deltafire** [comment]
Fixed @1a56151
