### ISSUE TITLE
Chip samples get corrupted when saving to MOD

### ISSUE THREAD

**Issue by SaxxonPike** [milkytracker/MilkyTracker#65]
1. Create a new tune
1. Create an 8-bit sample that is roughly 16 bytes long
1. Paint a waveform on that sample
1. Save as MOD
1. Reload to find that the beginning of the sample has been corrupted

This did not happen in the previous MilkyTracker release, and I suspect it has something to do with the 2 sample fix when saving to MOD. Maybe try adding padding at the beginning instead of messing up the looped sample?

**Comment by SyntaxErrol** [comment]
I think [this is fixed](https://github.com/milkytracker/MilkyTracker/commit/2dca0cee34d49a34c4c162fdc076272622b569f7) already but yeah, no release yet. :/

**Comment by Deltafire** [comment]
Also see 5fad619 - the sample is padded at the beginning for non-looping samples (looped samples are untouched).

**Comment by SaxxonPike** [comment]
Thank you. Looks like that change happened one month after the latest available release in November 2013. I'd forgotten to mention that was the release.
