### ISSUE TITLE
MilkyTracker.exe is not a valid win32 application

### ISSUE THREAD

**Issue by Liteshaft** [milkytracker/MilkyTracker#73]
This is occurred today when I downloaded the v1.00.00

My Computer Specs:
* Microsoft Windows XP Pro SP3 
* Intel Core2 CPU 6400 @ 2.13GHz, 0.97GB RAM

**Comment by dwhinham** [comment]
[milkytracker-1.00.00.zip](https://github.com/milkytracker/MilkyTracker/files/856354/milkytracker-1.00.00.zip)

@Liteshaft: I've done a quick build with XP support, but I don't have an XP machine handy right now. Would you care to test the build attached?

Cheers 😄

**Comment by Deltafire** [comment]
@dwhinham: yeah, I used the AppVeyor artifacts for the release not realising the -T v140_xp flag was not set; I'll upload the fixed binary to the releases page.

**Comment by Liteshaft** [comment]
@dwhinham 

Works like a charm, thanks!

**Comment by dwhinham** [comment]
Excellent. Thanks for the clear and concise bug report - as soon as I read the system specs I knew what it was. 😃
