### ISSUE TITLE
Custom Resolution Bug

### ISSUE THREAD

**Issue by xracecar** [milkytracker/MilkyTracker#76]
So with this new 1.0.0 update, there are obviously going to be bugs. Back in 0.90.85 custom resolutions worked fine. Now when I switched to 1.0.0 this happened. Switching the resolution to under my max resolution for other settings worked perfectly, so I don't know what to do but to wait for it to be fixed.
![screen shot 2017-03-31 at 3 44 35 pm](https://cloud.githubusercontent.com/assets/26825891/24568849/3d279448-1629-11e7-93a9-81a99e2579c6.png)

**Comment by dwhinham** [comment]
Thanks for the report - I was quickly able to reproduce this by trying an odd resolution of 64**1**x480.
Our graphics subsystem expected the width to be an multiple of 4, hence the strange corruption.

I've committed a fix for this which will go into the next release, but in the meantime can you please test the following package I've just built:
[milkytracker-1.00.00.dmg.zip](https://github.com/milkytracker/MilkyTracker/files/887157/milkytracker-1.00.00.dmg.zip)

Thanks! 😃

**Comment by xracecar** [comment]
I am currently running on El Capitan and it says for me to update to sierra, since I don't have 1.12

**Comment by dwhinham** [comment]
Oops - let's try that again (should hopefully run on 10.7 up):
[milkytracker-1.00.00.dmg.zip](https://github.com/milkytracker/MilkyTracker/files/887966/milkytracker-1.00.00.dmg.zip)

**Comment by xracecar** [comment]
Works perfectly. Thank you!
![screen shot 2017-04-01 at 4 30 30 pm](https://cloud.githubusercontent.com/assets/26825891/24582583/8c6e7c86-16f8-11e7-96f6-0645a47e93e2.png)
