### ISSUE TITLE
Frequencies and Bandwidth on Equalizers in SampleEditor are wrong

### ISSUE THREAD

**Issue by CorvusCorax** [milkytracker/MilkyTracker#82]
I had a look at the Equalizers in the SampleEditor, since they would be really useful for making and modifying ones own samples. What I noticed is, that the resonance frequency of the topmost freq band in the 10 band bandpass is below the Nyquist frequency for the samples, so they don't seem to cover the entire spectrum. This is bad.

![centerfreqtoolow](https://cloud.githubusercontent.com/assets/569222/24818591/7e268cc0-1be1-11e7-926f-209006e629d5.png)
<-- After running this filter over and over and over again (redo filter), eventually the only surviving and maximally amplified waveform should be a clear cut +1,-1, +1, -1, +1, -1,... sawtooth, but the waveform created is actually lower

(Note: Assuming a sampling rate of 8363Hz for the sample, this highest frequency is 4181.5Hz, or 0.5 samples)

So I had a look at the code...

```
/*  
 * bullshit trial and error values following because nobody knows 
 * how the EQ actually works
 *
 */

#include "EQConstants.h"
```

ehm... yeah... I guess that explains some :)

There is that nifty linux tool called "audacity" which is a wave editor. One of its features (consider this a low priority FEATURE REQUEST for Milkytracker) is a spectrum analyzer

This is the spectrum plot for a 32kb sample filled with the white noise generator:
![fa_whitenoise](https://cloud.githubusercontent.com/assets/569222/24818891/91e77fb6-1be2-11e7-96d2-3d8857d40c09.png)

as you can see, white noise has equal amplitude across all frequencies

in comparison to that pink noise:
![fa_pinknoise](https://cloud.githubusercontent.com/assets/569222/24818900/9e856b0c-1be2-11e7-965c-9b0b09868f0f.png)

Has a power spectrum proportional to 1/f and

brown noise
![fa_brownnoise](https://cloud.githubusercontent.com/assets/569222/24819012/2111707a-1be3-11e7-988d-5f50c3dc6e0a.png)

has a power spectrum proportional to 1/f²

This confirms that the noise generator do exactly what they should!!!

To test the Equalizers, you start with white noise, to have a nice level flat line across all frequencies, then filter it and plot the spectrum of the result.

I applied each filter 3 times in a row to magnify the results (since the spec plot has logscale it wouldn't be very visible otherwise)

3 band equalizer, configured as a Lowpass:
![fa_3bandlowpass](https://cloud.githubusercontent.com/assets/569222/24819160/c7bcb290-1be3-11e7-8bcd-433176b531d8.png)

The low frequencies are indeed amplified, but instead of mids and heights being surpressed, there's only two narrow band gaps around 500Hz and 2400Hz.
Most importantly, the high frequencies above 3kHz are not 4181.5Hz are not suppressed at all :( !

Similar for the mid band
![fa_3bandmidpass](https://cloud.githubusercontent.com/assets/569222/24819474/081c281a-1be5-11e7-933f-bac8636bd99c.png)

And the high band
![fa_3bandhighpass](https://cloud.githubusercontent.com/assets/569222/24819486/135f9658-1be5-11e7-860d-d851490dc73b.png)

Both suppression and amplification only affects a narrow band, with large gaps in between which are mostly unaffected. More importantly, the frequencies above 3kHz are untouched by any of the band filters.

This is also visible in the "you shall not pass" filter, (with all sliders at minimum) this should suppress ore or less anything, instead it only suppresses 3 comparably narrow bands

![fa_3bandnoneshallpass](https://cloud.githubusercontent.com/assets/569222/24819567/64df0e8c-1be5-11e7-8dc8-418dfe2a415e.png)

of which the top most does not reach the really high frequencies. (This is after applying the "youshallnotpass" filter 3 times.

Since this plot is the most descriptive, I also did the same for the 10 band filter:

![fa_10bandnoneshallpass](https://cloud.githubusercontent.com/assets/569222/24819590/901979ac-1be5-11e7-9cc5-f6b960230760.png)

This looks a little bit better, some of the bands actually overlap enough to cancel out whats in between them - but only in the low frequencies. The highest frequencies remain again untouched by the filter.

Looking at the code in src/tracker/SampleEditor.cpp ...

```
	float c4spd = getc4spd(sample->relnote, sample->finetune);
	float scale = c4spd / 44100.0f;
	
	Equalizer** eqs = new Equalizer*[par->getNumParameters()];
	
	// three band EQ
	if (par->getNumParameters() == 3)
	{
		for (pp_int32 i = 0; i < par->getNumParameters(); i++)
		{
			eqs[i] = new Equalizer();
			eqs[i]->CalcCoeffs(EQConstants::EQ3bands[i]*scale, EQConstants::EQ3bandwidths[i]*scale, c4spd, Equalizer::CalcGain(par->getParameter(i).floatPart));
		}
```

What this does (by rescaling the coefficients) is basically saying "treat my sampling frequency (of 8363 Hz +- finetune) as if it were 44100 Hz. This is relevant in respect to the constants in EQConstants.cpp as now 44100 is the sample rate and 22050Hz the Nyquist Freq.

however in EQConstants.cpp:
```
const float EQConstants::EQ3bands[3] = 
{
	80.0f,
	2500.0f,
	12000.0f
};

const float EQConstants::EQ3bandwidths[3] = 
{
	2500.0f*0.25f,
	2500.0f*0.5f,
	2500.0f
};
```
( and similar for EQ10)
the center frequency for the "heights" band is set to only 12kHz with a bandwidth of 2500Hz. (according to code in Equalicer.cpp that means the "less than 3 db of effect boundary" of the filter is at 12000 +- 1250Hz each. Any frequency above 13250Hz but below 22050Hz is effectively unaffected.

But we rescaled the coefficients, so divide by 44100/8363 and our topmost band now affects the frequency band of 2275 +- 237 Hz
Data in the sample at a Frequencz between 2512 Hz and 4181.5Hz remains effectively untouched.

Exactly what could be seen in the Spectrum Plot

So Suggestion:

1. Get rid of the "simulated/scaled" frequency and handling of offset/finetune for the equalizer. The topmost band center freq should equal Nyquist freq (sampling rate/2) excactly, so any pattern should be treated as sampled with 8363Hz for constant - unscaled coefficients

2. Adjust the band center frequencies to actually be displayed correctly
Band 10: 4181Hz
Band 9: 2090Hz
Band 8: 1045Hz
Band 7: 522Hz
Band 6: 261Hz
Band 5: 130Hz
Band 4: 65Hz
Band 3: 32Hz
Band 2: 16Hz
Band 1:  8Hz
(actual values are float, so should be based on 4181.5Hz! )

and something properly scaled for the 3 band

3. Adjust bandwidths for all bands so they overlap "just enough" - except for the lowest one which should be wide enough to cover all the way down to zero

I'm gonna experiment around with this a bit...

**Comment by alugarius** [comment]
there is an EQ in Milky??
cool

**Comment by Deltafire** [comment]
Thanks for the detailed description and fix :)
