### ISSUE TITLE
OSX: Unable to scale

### ISSUE THREAD

**Issue by bmosley** [milkytracker/MilkyTracker#90]
Config > Layout > Scale (x1, x2, etc) no longer working in 1.0. Regression from 90.86
![screen shot 2017-04-24 at 18 04 43](https://cloud.githubusercontent.com/assets/705077/25364637/a13cbdee-2918-11e7-9b05-70ae001ae831.png)

My eyes suck too much for these fancy new displays.

**Comment by dwhinham** [comment]
This was intentional as the window is now stretchable on macOS. To get the same effect as Scale 2x, you can set a custom resolution of half your actual desktop resolution, then full-screen the window.

**Comment by bmosley** [comment]
This is great and much improved. Been using 90.86 for so long I didn't think to try dragging the window. Thanks for pointing this out!

**Comment by dwhinham** [comment]
You're welcome. Enjoy! 😃
