### ISSUE TITLE
OSX: Not possible to insert rows

### ISSUE THREAD

**Issue by Deltafire** [milkytracker/MilkyTracker#96]
Insert and shift-insert is mapped to insert note and insert row respectively. The insert key is missing from mac keyboards.

Previous versions had an option in preferences to remap the insert key, but the preferences menu is now disabled (see #78).

**Comment by martinmosegaard** [comment]
I don't understand how to use this fix? I don't have an F13 key (?)

**Comment by Deltafire** [comment]
It's changed from "not possible" to "difficult" ;)

More information on PR #97.

**Comment by entozoon** [comment]
Please re-open this. Using a macbook I can't figure out a way to insert rows which is.. kinda a dealbreaker

**Comment by Deltafire** [comment]
Try this build, insert is mapped to alt-backspace (which makes a bit of sense, since it's the opposite of delete row). Use shift-alt-backspace to add a row to the entire pattern instead of just the current track.

[milkytracker-1.03.00-Darwin.dmg.zip](https://github.com/milkytracker/MilkyTracker/files/5758165/milkytracker-1.03.00-Darwin.dmg.zip)

**Comment by johnedvard** [comment]
I just started using MilkyTracker and got frustrated that some shortcuts did not work (even with an external keyboard that has an insert key), so I was really happy to find this page. And only 4 days old as well. Just in time. Thanks!
